package com.rock.metadata.model;

import jakarta.persistence.*;
import lombok.*;
import java.time.LocalDateTime;

@Entity
@Table(name = "meta_table", indexes = {
    @Index(name = "idx_meta_table_ds_job", columnList = "datasource_id, crawl_job_id"),
    @Index(name = "idx_meta_table_schema", columnList = "schema_id")
})
@Getter @Setter @NoArgsConstructor
public class MetaTable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "datasource_id", nullable = false)
    private Long datasourceId;

    @Column(name = "crawl_job_id", nullable = false)
    private Long crawlJobId;

    @Column(name = "schema_id")
    private Long schemaId;

    @Column(name = "schema_name")
    private String schemaName;

    @Column(name = "table_name", nullable = false)
    private String tableName;

    @Column(name = "full_name", nullable = false)
    private String fullName;

    /** TABLE, VIEW, MATERIALIZED VIEW, SYSTEM TABLE, etc. */
    @Column(name = "table_type", length = 64)
    private String tableType;

    @Column(columnDefinition = "TEXT")
    private String remarks;

    /** DDL definition for views */
    @Column(columnDefinition = "TEXT")
    private String definition;

    @Column(name = "row_count")
    private Long rowCount;

    /** Timestamp of last row count update */
    @Column(name = "row_count_updated_at")
    private LocalDateTime rowCountUpdatedAt;

    // ===== Business attributes (LLM enriched) =====

    /** Business display name, e.g. "用户表" */
    @Column(name = "display_name", length = 512)
    private String displayName;

    /** Business description generated by LLM */
    @Column(name = "business_description", columnDefinition = "TEXT")
    private String businessDescription;

    /** Business domain, e.g. "交易域", "用户域", "风控域" */
    @Column(name = "business_domain", length = 128)
    private String businessDomain;

    /** Data owner / responsible person */
    @Column(length = 128)
    private String owner;

    /** Importance level: CORE, IMPORTANT, NORMAL, TRIVIAL */
    @Enumerated(EnumType.STRING)
    @Column(name = "importance_level", length = 16)
    private ImportanceLevel importanceLevel;

    /** Data quality score (0-100) */
    @Column(name = "data_quality_score")
    private Integer dataQualityScore;

    // ===== LLM analysis tracking =====

    /** Timestamp of last LLM analysis */
    @Column(name = "last_analyzed_at")
    private LocalDateTime lastAnalyzedAt;

    /** LLM analysis confidence (0.0 - 1.0) */
    @Column(name = "analysis_confidence")
    private Double analysisConfidence;
}
