package com.rock.metadata.model;

import jakarta.persistence.*;
import lombok.*;
import java.time.LocalDateTime;

@Entity
@Table(name = "meta_column", indexes = {
    @Index(name = "idx_meta_column_table", columnList = "table_id")
})
@Getter @Setter @NoArgsConstructor
public class MetaColumn {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "table_id", nullable = false)
    private Long tableId;

    @Column(name = "column_name", nullable = false)
    private String columnName;

    @Column(name = "ordinal_position")
    private int ordinalPosition;

    @Column(name = "data_type", length = 128)
    private String dataType;

    /** Database-specific type name, e.g. "character varying", "int4" */
    @Column(name = "db_specific_type_name", length = 256)
    private String dbSpecificTypeName;

    @Column(name = "column_size")
    private int columnSize;

    @Column(name = "decimal_digits")
    private int decimalDigits;

    @Column(name = "is_nullable")
    private boolean nullable;

    @Column(name = "default_value")
    private String defaultValue;

    @Column(name = "auto_incremented")
    private boolean autoIncremented;

    @Column(name = "is_generated")
    private boolean generated;

    @Column(name = "is_hidden")
    private boolean hidden;

    /** Column definition / expression for generated columns */
    @Column(name = "column_definition", columnDefinition = "TEXT")
    private String columnDefinition;

    @Column(name = "part_of_primary_key")
    private boolean partOfPrimaryKey;

    @Column(name = "part_of_foreign_key")
    private boolean partOfForeignKey;

    @Column(name = "part_of_index")
    private boolean partOfIndex;

    @Column(length = 4096)
    private String remarks;

    // ===== Business attributes (LLM enriched) =====

    /** Business display name, e.g. "age" -> "年龄" */
    @Column(name = "display_name", length = 256)
    private String displayName;

    /** Business description generated by LLM */
    @Column(name = "business_description", length = 4096)
    private String businessDescription;

    /** Business data type: AMOUNT, RATE, DATE, CODE, ENUM, ID, NAME, ADDRESS, etc. */
    @Column(name = "business_data_type", length = 64)
    private String businessDataType;

    /** Sample values for understanding the column content */
    @Column(name = "sample_values", length = 1024)
    private String sampleValues;

    /** Value range description, e.g. "0-150", "A/B/C" */
    @Column(name = "value_range", length = 512)
    private String valueRange;

    // ===== Security attributes =====

    /** Sensitivity level: PUBLIC, INTERNAL, SENSITIVE, HIGHLY_SENSITIVE */
    @Enumerated(EnumType.STRING)
    @Column(name = "sensitivity_level", length = 32)
    private SensitivityLevel sensitivityLevel;

    /** Sensitivity type: PII, FINANCIAL, MEDICAL, CREDENTIAL, LOCATION, etc. */
    @Column(name = "sensitivity_type", length = 64)
    private String sensitivityType;

    /** Masking strategy: FULL_MASK, PARTIAL_MASK, HASH, ENCRYPT, NONE */
    @Column(name = "masking_strategy", length = 32)
    private String maskingStrategy;

    /** Compliance flags, comma-separated: GDPR, CCPA, HIPAA, PCI_DSS, etc. */
    @Column(name = "compliance_flags", length = 256)
    private String complianceFlags;

    // ===== LLM analysis tracking =====

    /** Timestamp of last LLM analysis */
    @Column(name = "last_analyzed_at")
    private LocalDateTime lastAnalyzedAt;

    /** LLM analysis confidence (0.0 - 1.0) */
    @Column(name = "analysis_confidence")
    private Double analysisConfidence;
}
